name: "Update and Deploy"
on:
  schedule:
    - cron:  '0 0,6,12,16 * * *'
  workflow_dispatch:

jobs:
  Build:
    name: Build and Deploy ErrorPortal to Cloudflare
    runs-on: ubuntu-latest
    steps:
      - name: Atomi CI Environment
        uses: kirinnee/atomici-action@v2.3.1

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Emulate Nix Shell
        env:
          NIXPKGS_ALLOW_UNFREE: "1"
        run: nix-shell nix/shells.nix -A ci --run scripts/export_path.sh
      - name: Build Artifact
        run: scripts/build.sh
      - name: Deploy Error Portal
        run: scripts/publish_cloudflare.sh
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: "error-portal"
          DIRECTORY: build
        
